---
openapi: 3.0.0
info:
  title: Todo API Server
  description: An API for ToDo lists
  version: 1.0.0
servers:
- url: /
paths:
  /todo:
    get:
      summary: Get all todo tasks.
      responses:
        "200":
          description: A JSON array of todo tasks.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Task'
    post:
      summary: Add a todo task
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Task'
        required: true
      responses:
        "201":
          description: Task was added successfully.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
        "400":
          description: Invalid input or bad Json syntax.
        "409":
          description: Task already exists.
    patch:
      summary: Update a todo task by id.
      requestBody:
        description: The new Task with the updated fields.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Task'
      responses:
        "200":
          description: The request received and understood and item updated.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
        "400":
          description: Server did not understand the request due to bad syntax.
        "404":
          description: The specified task ID is not found.
  /todo/{taskId}:
    get:
      summary: Get a todo task by id.
      parameters:
      - name: taskId
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: integer
          format: int64
          example: 1
      responses:
        "200":
          description: Task was retrieved successfully.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
        "400":
          description: The specified task ID is invalid (not a number).
        "404":
          description: The specified task ID is not found.
    delete:
      summary: Delete a todo task by id.
      parameters:
      - name: taskId
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: integer
          format: int64
          example: 1
      responses:
        "200":
          description: The request received and understood and item deleted.
        "400":
          description: Server did not understand the request due to bad syntax.
        "404":
          description: The specified task ID is not found.
components:
  schemas:
    Task:
      required:
      - complete
      - id
      - title
      type: object
      properties:
        id:
          type: integer
          format: int64
        title:
          type: string
          description: task title
          example: clean the room
        complete:
          type: boolean
          example: true
