name: Todo tests

on:
  push:
    branches: [ development ]
  pull_request:
    branches: [ main ]

jobs:
  code_testing:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: install golang
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Run unit testing
      run: go test *.go

    - name: Build and push docker image
      uses: mr-smithers-excellent/docker-build-push@v5
      with:
        image: islamwalid/todo-api
        registry: docker.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
